// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLectureDetails(arg1) {
  return window['go']['main']['App']['GetLectureDetails'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Scrape() {
  return window['go']['main']['App']['Scrape']();
}

export function SearchLectures(arg1) {
  return window['go']['main']['App']['SearchLectures'](arg1);
}
