// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetLectureDetails(arg1:number):Promise<domain.Lecture>;

export function Greet(arg1:string):Promise<string>;

export function Scrape():Promise<void>;

export function ScrapeTest():Promise<void>;

export function SearchLectures(arg1:domain.SearchQuery):Promise<Array<domain.LectureSummary>>;
